# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target '0610' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 0610
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '4.10.1'
  pod 'SVProgressHUD'
  pod 'SwiftyBeaver'
  pod 'SwifterSwift'
  pod 'MarqueeLabel'
#  pod 'JXMarqueeView'
#  pod "ShowAPI_SDK"

  pod 'Fabric'
  pod 'Crashlytics'

end
