# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target '0610' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 0610
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 5.0'
  pod 'SVProgressHUD'
  pod 'SwiftyBeaver'
  pod 'SwifterSwift'
  pod 'MarqueeLabel'
  pod 'JXMarqueeView'
  
end
